name: backend
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2024.11.26=haa95532_0
  - libffi=3.4.4=hd77b12b_1
  - openssl=3.0.15=h827c3e9_0
  - pip=24.2=py310haa95532_0
  - python=3.10.16=h4607a30_1
  - setuptools=75.1.0=py310haa95532_0
  - sqlite=3.45.3=h2bbff1b_0
  - tk=8.6.14=h0416ee5_0
  - vc=14.40=haa95532_2
  - vs2015_runtime=14.42.34433=h9531ae6_2
  - wheel=0.44.0=py310haa95532_0
  - xz=5.4.6=h8cc25b3_1
  - zlib=1.2.13=h8cc25b3_1
  - pip:
      - absl-py==2.3.1
      - altair==6.0.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.12.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - asttokens==3.0.1
      - astunparse==1.6.3
      - async-lru==2.0.5
      - attrs==25.4.0
      - babel==2.17.0
      - bcrypt==4.2.1
      - beautifulsoup4==4.14.3
      - bleach==6.3.0
      - blinker==1.9.0
      - cachecontrol==0.14.1
      - cachetools==5.5.0
      - certifi==2024.12.14
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - click==8.1.8
      - colorama==0.4.6
      - comm==0.2.3
      - contourpy==1.3.2
      - cryptography==44.0.0
      - cycler==0.12.1
      - debugpy==1.8.19
      - decorator==5.2.1
      - defusedxml==0.7.1
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - fastapi==0.127.1
      - fastjsonschema==2.21.2
      - firebase-admin==6.6.0
      - flask==3.1.0
      - flask-cors==5.0.0
      - flatbuffers==25.12.19
      - fonttools==4.61.1
      - fqdn==1.5.1
      - gast==0.4.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-api-core==2.24.0
      - google-api-python-client==2.157.0
      - google-auth==2.37.0
      - google-auth-httplib2==0.2.0
      - google-auth-oauthlib==1.0.0
      - google-cloud-core==2.4.1
      - google-cloud-firestore==2.19.0
      - google-cloud-storage==2.19.0
      - google-crc32c==1.6.0
      - google-pasta==0.2.0
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.66.0
      - grpcio==1.69.0
      - grpcio-status==1.69.0
      - h11==0.16.0
      - h5py==3.15.1
      - httpcore==1.0.9
      - httplib2==0.22.0
      - httpx==0.28.1
      - idna==3.10
      - ipykernel==7.1.0
      - ipython==8.37.0
      - isoduration==20.11.0
      - itsdangerous==2.2.0
      - jax==0.4.30
      - jaxlib==0.4.30
      - jedi==0.19.2
      - jinja2==3.1.5
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-client==8.7.0
      - jupyter-core==5.9.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.5.1
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - keras==2.12.0
      - kiwisolver==1.4.9
      - lark==1.3.1
      - libclang==18.1.1
      - markdown==3.10
      - markupsafe==3.0.2
      - matplotlib==3.7.1
      - matplotlib-inline==0.2.1
      - mistune==3.2.0
      - ml-dtypes==0.5.4
      - msgpack==1.1.0
      - narwhals==2.14.0
      - nbclient==0.10.4
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - notebook-shim==0.2.4
      - numpy==1.23.5
      - oauthlib==3.3.1
      - opt-einsum==3.4.0
      - overrides==7.7.0
      - packaging==25.0
      - pandas==2.0.2
      - pandocfilters==1.5.1
      - parso==0.8.5
      - pillow==12.0.0
      - platformdirs==4.5.1
      - prometheus-client==0.23.1
      - prompt-toolkit==3.0.52
      - proto-plus==1.25.0
      - protobuf==4.25.8
      - psutil==7.2.0
      - pure-eval==0.2.3
      - pyarrow==22.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pycparser==2.22
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydeck==0.9.1
      - pydot==1.4.2
      - pygments==2.19.2
      - pyjwt==2.10.1
      - pyparsing==3.2.1
      - python-dateutil==2.9.0.post0
      - python-json-logger==4.0.0
      - python-multipart==0.0.21
      - pytz==2025.2
      - pywinpty==3.0.2
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - referencing==0.37.0
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rpds-py==0.30.0
      - rsa==4.9
      - scipy==1.15.3
      - send2trash==1.8.3
      - six==1.17.0
      - smmap==5.0.2
      - soupsieve==2.8.1
      - stack-data==0.6.3
      - starlette==0.50.0
      - streamlit==1.52.2
      - tenacity==9.1.2
      - tensorboard==2.12.3
      - tensorboard-data-server==0.7.2
      - tensorflow==2.12.1
      - tensorflow-estimator==2.12.0
      - tensorflow-intel==2.12.1
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==3.2.0
      - terminado==0.18.1
      - tinycss2==1.4.0
      - toml==0.10.2
      - tomli==2.3.0
      - tornado==6.5.4
      - traitlets==5.14.3
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - uri-template==1.3.0
      - uritemplate==4.1.1
      - urllib3==2.3.0
      - uv==0.9.18
      - uvicorn==0.40.0
      - watchdog==6.0.0
      - wcwidth==0.2.14
      - webcolors==25.10.0
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - werkzeug==3.1.3
      - wrapt==1.14.2
prefix: C:\Users\prasa\miniconda3\envs\backend
